import { type NextPage } from "next";
import Head from "next/head";
import Nav from "../components/Nav";
import Footer from "../components/Footer";
import PreHeader from "../components/PreHeader";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";

import GetDataFeed from "../components/DataFeed";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>T3-API</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className="bg-slate-700">
      <PreHeader/>

      <Nav/>
        <main className="p-10">
          <div>
            <GetDataFeed/>
          </div>
        </main>
      <Footer/>
    </div>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
